version: '3'
services:
    mongodb:
        container_name: db
        image: mongo
        ports:
            - "27017:27017"
        #    command: mongod --smallfiles --auth --bind_ip_all
        environment:
            MONGO_INITDB_ROOT_USERNAME: nunjo
            MONGO_INITDB_ROOT_PASSWORD: dougals
        volumes:
            - ./data:/data/db
        labels:
            - "traefik.enable=true"
            - 'traefik.tcp.routers.mongo.rule=HostSNI(`*`)'
            - 'traefik.tcp.routers.mongo.entrypoint=mongo'
            - 'traefik.tcp.services.mongo.loadbalancer.server.port=27017'

    middleware:
        image: docker.io/traefik:v2.9
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.db.address=:27017"
        ports:
            - "80:80"
            - "8080:8080"
            - "8443:443"
            - "3306:3306"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - "traefik.http.routers.traefik.entrypoints=web"
            - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"

    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.entrypoints=web"
            - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
            - "traefik.http.middlewares.whoami-codespaces.stripprefix.prefixes=/whoami"
            - "traefik.http.routers.whoami-codespaces.rule=PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami-codespaces.middlewares=whoami-codespaces@docker"

